version: '3'
services:

    #PHP Service shorted link
    app-link:
        build:
            context: ./app
            dockerfile: Dockerfile
            args:
                user: user
                uid: 1000
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes:
            - ./app/:/var/www
        networks:
            - app_network

    #Nginx Service
    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./app:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - app_network

    #MySQL Service
    db:
        image: mysql
        container_name: db
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - db_data:/var/lib/mysql/
            - ./docker/mysql:/docker-entrypoint-initdb.d
        networks:
            - app_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        container_name: phpmyadmin
        environment:
            PMA_HOST: db
        ports:
            - "8080:80"
        networks:
            - app_network

#Docker Networks
networks:
    app_network:
        driver: bridge

#Volumes
volumes:
    db_data:
        driver: local